### ISSUE TITLE
Unresolved reference 'mlp'

### ISSUE THREAD

**Issue by WillieMaddox** [PacktPublishing/Advanced-Machine-Learning-with-Python#1]
In CH2/DBN.py I have and unresolved reference to:

``` python
from mlp import HiddenLayer
```

Is there a separate python package for this?

I tried,

``` bash
pip install mlp
```

but there is no HiddenLayer submodule.

Thanks.

**Comment by ghost** [comment]
I don't know if you ever found the result but the book is using MLP from this site [deeplearning.net](http://deeplearning.net/tutorial/mlp.html)
